spring:
  web:
    resources:
      static-locations:
        - "file:/root/app/mock-data/front/dist"    # linux发布机器
        - "file:D:/git/demo/mock-data/front/dist"  # windows机器
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # spring boot 2.6.x结合swagger3.0.0不兼容问题

